#!/bin/bash

set -o errexit

if [ ! -d .git ]
then
  echo "This repository contains code that can be used to execute Gene Set Omic Analysis (GSOA)..." >  README.md
  git init
  git add --all .
  git commit -m "first commit"
  git remote add origin git@bitbucket.org:srp33/gsoa.git
  git push -u origin master
fi

git add --all .
git commit -m "`date`"
git push -u origin master
