#!/bin/bash

if [ "$1" == "" ]
then
  echo Please specify a script to run.
  exit 1
fi

./commit_git
vagrant ssh --command "~/update_git"

vagrant ssh --command "pwd"
#vagrant ssh --command "~/scripts/$1"
