#!/bin/bash

if [ "$1" == "" ]
then
  echo Please specify a script to run.
  exit 1
fi

./commit_git
#vagrant ssh --command "nohup ~/update_git > ~/nohup_${1}.out &"
vagrant ssh --command "nohup echo ~/update_git > ~/nohup_${1}.out &"

#vagrant ssh --command "~/scripts/$1"
