#!/bin/bash

if [ "$1" == "" ]
then
  echo Please specify a script to run.
  exit 1
fi

./commit_git
vagrant ssh --command "~/update_git"

vagrant ssh --command "rm -f ~/nohup_${1}.out"
vagrant ssh --command "nohup ~/scripts/$1 > ~/nohup_${1}.out"
